
!ConfigurationOfFileTree methodsFor: 'versions' stamp: 'dkh 1/31/2012 15:24'!
version100: spec
    <version: '1.0' imports: #('1.0-baseline')>
    spec
        for: #'common'
        do: [ 
            spec blessing: #'development'.
            spec
                description:
                    '1.0 (dkh.2):
- change the description for FileTree repository to filetree:// to be consistent with other Metacello descriptions...
1.0 (dkh.3):
- missing methods needed to run in Pharo1.3 #13315
1.0 (dkh.4):
- fix Issue 13: Monticello branches not handled correctly
  https://github.com/finworks/smallsource/issues/13
1.0 (dkh.5):
- woops, real fix for Issue 13...
1.0 (dkh.6):
- merge MonticelloFileTree-dkh.58 and MonticelloFileTree-Core-revelations.13
- a little refactoring for Montigitto support'.
            spec author: 'dkh'.
            spec timestamp: '1/31/2012 15:23'.
            spec package: 'MonticelloFileTree-Core' with: 'MonticelloFileTree-Core-dkh.14' ].
    spec
        for: #'gemstone'
        do: [ spec package: 'MonticelloFileTree-GemStone-Extensions' with: 'MonticelloFileTree-GemStone-Extensions-revelations.11' ]! !
